version: 2
jobs:
  prepare_build_test:
    docker:
      - image: balasys/zorpgpl-circleci:7.0
    environment:
      PACKAGE: iptables-addons
      OBS_PROJECT_DIR: security:Zorp:7:0:1/iptables-addons
    working_directory: ~/zorp-iptables-addons
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --init
      - run: source ci/build.sh
      - run: source ci/obs_prepare.sh
      - run: source ci/obs_commit.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare_build_test
